Ext.define('Admin.view.user.UserGridPanel', {
	extend:Ext.grid.Panel, 
		xtype:'userGridPanel', 
		title:'用户管理列表',
		 id:'userGridPanel',
		 dockedItems:[
		{xtype:'toolbar', 
		items:[
		{xtype:'combobox',
		 fieldLabel:'',
		 name:'searchFieldName',
		 reference:'searchFieldName', 
		store:{
		proxy:{type:'memory', reader:'array'}, 
			fields:['key', 'value'],
			 data:[['用户名', 'userName'], ['密码', 'password']]},
			 queryMode:'local', 
			displayField:'key',
			 valueField:'value', 
			value:'userName', allowBlank:false},
			 '-', {xtype:'textfield', name:'searchFieldValue', 
reference:'searchFieldValue'}, '-',
			 {text:'快捷查询', tooltip:'快捷查询', 
			iconCls:'x-fa fa-search', handler:'search'}, 
			'-', {xtype:'button',iconCls:'x-fa fa-trash',
			 text:'批量删除', listeners:{click:'deleteUsers'}}, '-',
			 {xtype:'button',text:'添加用户', tooltip:'添加',
			 iconCls:'x-fa fa-plus', handler:'openAddWindow'},'-',
			 {xtype:'button',text:'角色', tooltip:'角色',
			 iconCls:'x-fa fa-plus',handler:'addRoleWindow' }, '-',
			 {xtype:'button',text:'修改个人信息', tooltip:'修改个人信息',
			 iconCls:'x-fa fa-exchange', handler:'updateMessage'}]}],
			 selModel:{selType:'checkboxmodel'}, bind:'{userlists}',
			 layout:'fit', columns:[{header:'ID', dataIndex:'id', flex:1},
			 {header:'用户名', dataIndex:'userName', flex:1},
			 {header:'角色名', dataIndex:'roleName', flex:1}, 
			{header:'部门名', dataIndex:'deptName', flex:1}, 
			{xtype:'actioncolumn', 
			items:[
			{xtype:'button', iconCls:'x-fa fa-pencil',tooltip:'编辑', handler:'openEditWindow'}, {
			xtype:'button', iconCls:'x-fa fa-trash', tooltip:'删除',handler:'deleteUser'}],
				 cls:'content-column', width:120, text:'操作', tooltip:'操作 ', flex:1}],
				 bbar:{xtype:'pagingtoolbar', bind:'{userlists}', displayInfo:true, displayMsg:'Displaying topics {0} - {1} of {2}',
				 emptyMsg:'No topics to display', items:['-', 
]}});